spring:
  application:
    name: user_manege
  datasource:
    url: jdbc:mysql://localhost:3306/wj_project
    username: root
    password: 619820
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 64800
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值